on:
  push:
    branches:
    - master # Changed to avoid unnecessary builds. Change back to master to enable building
name: Build Master
env:
  PLUGIN_BUILD_VERSION: 1.0.1 # How to make this external? Get data from plugin.json
  RACK_SDK_VERSION: 2.3.0
  ARCH: lin
jobs:
  fetch_SDK:
    name: Fetch SDK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    #- uses: actions/checkout@V2
#      with:
#        path: "testpath"
    - name: Fetch SDK
#      uses: ./.github/actions/rack_sdk
      run: |
          curl -L https://vcvrack.com/downloads/Rack-SDK-2.0.3-lin.zip -o Rack-SDK-2-lin.zip
          unzip -o -d Rack-SDK-lin Rack-SDK-2-lin.zip
          rm Rack-SDK-2-lin.zip
          curl -L https://vcvrack.com/downloads/Rack-SDK-2.0.3-win.zip -o Rack-SDK-2-win.zip
          unzip -o -d Rack-SDK-win Rack-SDK-2-win.zip
          rm Rack-SDK-2-win.zip
          mkdir -p plugins
  build_Linux:
    name: Build Linux
    runs-on: ubuntu-latest
    needs: [fetch_SDK]
    steps:
    - uses: actions/checkout@master
    - name: Build Linux
      uses: ./.github/actions/build_linux
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: JLmod-${{ env['PLUGIN_BUILD_VERSION'] }}-lin.zip
        path: ./dist/JLmod-${{ env['PLUGIN_BUILD_VERSION'] }}-lin.zip
  build_win:
    name: Build Windows
    runs-on: ubuntu-latest
    needs: [fetch_SDK]
    steps:
    - uses: actions/checkout@master
    - name: Build Windows
      uses: ./.github/actions/build_win
    - name: Save artifact
      uses: actions/upload-artifact@v1
      with:
        name: JLmod-${{ env['PLUGIN_BUILD_VERSION'] }}-win.zip
        path: ./dist/JLmod-${{ env['PLUGIN_BUILD_VERSION'] }}-win.zip
  combineDist:
    name: Combine Distributions
    runs-on: ubuntu-latest
    needs: [build_Linux, build_win]
    steps:
    - name: Download Linux
      uses: actions/download-artifact@v1
      with:
        name: JLmod-${{ env['PLUGIN_BUILD_VERSION'] }}-lin.zip
        path: ./dist
    - name: Download Windows
      uses: actions/download-artifact@v1
      with:
        name: JLmod-${{ env['PLUGIN_BUILD_VERSION'] }}-win.zip
        path: ./dist
    - name: Unzip
      run: unzip -o "dist/*.zip" -d ./dist
    - name: Remove Zipfiles
      run: rm dist/*.zip
    - name: Combine
      run: cd dist && zip -q -9 -r JLmod-${{ env['PLUGIN_BUILD_VERSION'] }}.zip ./JLmod
    - name: Save artifact
      uses: actions/upload-artifact@v1
      with:
        name: JLmod-${{ env['PLUGIN_BUILD_VERSION'] }}.zip
        path: ./dist/JLmod-${{ env['PLUGIN_BUILD_VERSION'] }}.zip
